# Numpy

- Multidimensional array : NumPy's main data structure is the multidimensional array (numpy.ndarray), which provides efficient storage and manipulation of multidimensional data. In machine learning, data is often represented as multidimensional arrays, so NumPy provides a convenient way to manipulate and process this data.

- Mathematical functions : NumPy provides a wealth of mathematical functions, covering basic mathematical operations, linear algebra, Fourier transform, etc. These functions are essential for the implementation and optimization of machine learning algorithms.

- Fast computing : NumPy's underlying implementation uses C language, so its computing speed is very fast. NumPy's efficient computing ability is very helpful when processing large-scale data.

- Broadcasting : NumPy’s broadcasting functionality allows arithmetic operations to be performed on arrays of different sizes, making the code more concise, more readable, and reducing memory consumption.

- Random number generation : NumPy provides powerful random number generation functions, including random number generators with multiple distributions. This is very useful in simulating data, initializing model parameters, etc.

- Integration with other libraries : NumPy is tightly integrated with many other Python libraries (such as SciPy, Pandas, Matplotlib, etc.), making it easy to exchange data between them and jointly build complex data processing and visualization pipelines.

- Linear algebra operations : NumPy provides a wealth of linear algebra operations, such as matrix multiplication, inversion, eigenvalue decomposition, etc. This is crucial for many machine learning algorithms, especially deep learning algorithms.

- Memory Optimization : NumPy’s data structures are optimized to utilize memory more efficiently, which is crucial especially for large datasets and computationally intensive tasks.

1. Create an array

**np.array()** Convert a Python list to a NumPy array 

In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


2. Array shape

Use  **np.shape**, **np.reshape()**, or  **np.ndarray.shape** to view the array shape, and use to  **np.reshape()** change the array shape.

In [4]:
import numpy as np

my_array = np.array([[1,2,3],
                    [4,5,6]])
print(f'Array shape: {my_array.shape}')

reshaped_array = my_array.reshape(3,2)
reshaped_array = np.reshape(my_array, (3,2))
print(f'Reshaped array: {reshaped_array.shape}')

Array shape: (2, 3)
Reshaped array: (3, 2)


3. Array dimensions

Use  **np.ndim** or  **np.ndarray.ndim** to view array dimensions.

In [5]:
import numpy as np

my_array = np.array([[1,2,3],
                    [4,5,6]])
print(f'Array dimensions: {my_array.ndim}')

Array dimensions: 2


4. Array size

Use **np.size** or  **np.ndarray.size** to view the array size.

In [6]:
import numpy as np

my_array = np.array([[1,2,3],
                    [4,5,6]])
print(f'Array size: {my_array.size}')

Array size: 6


5. Array data type

Use  np.dtype or  np.ndarray.dtype view array data types.

In [7]:
import numpy as np

my_array = np.array([[1,2,3],
                    [4,5,6]])
print(f'Array data type: {my_array.dtype}')

Array data type: int64


6.  Array type conversion

Use  np.astype() or  np.ndarray.astype convert array data types.

In [8]:
import numpy as np

my_array = np.array([[1,2,3],
                    [4,5,6]])
print(f'Array data type: {my_array.dtype}')

converted_array = my_array.astype(float)
print(f'Converted array data type: {converted_array.dtype}')

Array data type: int64
Converted array data type: float64


7. Array filling

Use  np.zeros(), np.ones(), np.full() or  np.empty() to create an array of specific fill values.

In [9]:
import numpy as np

# create an array of zeros
zeros_array = np.zeros((3,4))
print(f'Zeros array: {zeros_array}')

# create an array of ones
ones_array = np.ones((3,4))
print(f'Ones array: {ones_array}')

# create an empty array
empty_array = np.empty((2,3))
print(f'Empty array: {empty_array}')

# create an array of specific value
full_array = np.full((3,3), 6)
print(f'Full array: {full_array}')


Zeros array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Empty array: [[0. 0. 0.]
 [0. 0. 0.]]
Full array: [[6 6 6]
 [6 6 6]
 [6 6 6]]


8. Array Range

Uses  np.arange() or  np.linspace() creates an array of the specified range.

In [13]:
import numpy as np

# create an array within a range
arange_array = np.arange(0, 10, 2)
print(f'Arange array: {arange_array}')

# create an array with evenly spaced values
linspace_array = np.linspace(0, 10, 10)
print(f'Linspace array: {linspace_array}')

Arange array: [0 2 4 6 8]
Linspace array: [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


9. Random Array

 Create a random array using  np.random.rand(), np.random.randn(), np.random.randint() or  .np.random.random()

In [14]:
import numpy as np

# create an array that is uniformly distributed
rand_array = np.random.rand(3,3)
print(f'Random array: {rand_array}')

# create an array that is normally distributed
randn_array = np.random.randn(3,3)
print(f'Random array: {randn_array}')

# create an array of random integers in the specified range
randint_array = np.random.randint(0, 10, size = (3,3))
print(f'Random array: {randint_array}')

# create an array of random values that are uniformlly distributed
random_array = np.random.random((3,3))
print(f'Random array: {random_array}')

Random array: [[0.09325266 0.15125748 0.12734528]
 [0.98418047 0.8858867  0.89746941]
 [0.19367851 0.52484187 0.87756016]]
Random array: [[-0.97364363  0.0070161  -0.741358  ]
 [-1.43870064 -0.21155593 -1.99129256]
 [-1.33327009  0.54545031  1.67329449]]
Random array: [[3 4 4]
 [0 8 8]
 [1 5 5]]
Random array: [[0.20584397 0.06704059 0.1540186 ]
 [0.93502006 0.2731176  0.38252106]
 [0.19129072 0.645807   0.05843883]]


10. Array Indexing

Use array indexing to get a specific element or row.

In [16]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(f'Array: {my_array}')
print(f'Array shape: {my_array.shape}')
# access an element
print(f'The first element: {my_array[0,0]}')
print(f'The last element: {my_array[-1,-1]}')

# access a row
print(f'The first row: {my_array[0,:]}')
print(f'The last row: {my_array[-1,:]}')

# access a column
print(f'The first column: {my_array[:,0]}')
print(f'The last column: {my_array[:,-1]}')

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape: (3, 3)
The first element: 1
The last element: 9
The first row: [1 2 3]
The last row: [7 8 9]
The first column: [1 4 7]
The last column: [3 6 9]


11. Array Slicing

Use the slice operation to get a specific range of array elements.

[row:row, column:column]

In [24]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# slice the array
sliced_array = my_array[:2, 1:]
print(f'Sliced array: {sliced_array}')

slice_array = my_array[1:, 1:3]
print(f'Slice array: {slice_array}')

Sliced array: [[2 3]
 [5 6]]
Slice array: [[5 6]
 [8 9]]


12. Array shape changes

Use  np.reshape(), np.ravel() , or  np.flatten() to reshape an array.

In [29]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(f'Array: {my_array}')
print(f'Array shape: {my_array.shape}')

# reshape the array
reshaped_array = my_array.reshape(9)
print(f'Reshaped array: {reshaped_array}')
print(f'Reshaped array shape: {reshaped_array.shape}')

reshaped_array = my_array.ravel()
print(f'Raveled array: {reshaped_array}')
print(f'Raveled array shape: {reshaped_array.shape}')

reshaped_array = my_array.flatten()
print(f'Flattened array: {reshaped_array}')
print(f'Flattened array shape: {reshaped_array.shape}')

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape: (3, 3)
Reshaped array: [1 2 3 4 5 6 7 8 9]
Reshaped array shape: (9,)
Raveled array: [1 2 3 4 5 6 7 8 9]
Raveled array shape: (9,)
Flattened array: [1 2 3 4 5 6 7 8 9]
Flattened array shape: (9,)


13. Array Transpose

Use  np.transpose() or  np.ndarray.T to transpose an array.

In [34]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]])
print(f'Array shape: {my_array.shape}')

# Transpose the array
transposed_array = my_array.T
print(f'Transposed array: {transposed_array}')
print(f'Transposed array shape: {transposed_array.shape}')

Array shape: (4, 3)
Transposed array: [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transposed array shape: (3, 4)


14. Array Concatenation

 Concatenate arrays using  np.concatenate(), np.vstack(), np.hstack() or  .np.column_stack()

In [36]:
import numpy as np

# create an array
array1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
array2 = np.array([[10,11,12],
                    [13,14,15],
                    [16,17,18]])

# concatenate the arrays along the rows
hstacked_array = np.hstack((array1, array2))
print(f'Horizontally stacked array: {hstacked_array}')
print(f'Horizontally stacked array shape: {hstacked_array.shape}')

# concatenate the arrays along the columns
vstacked_array = np.vstack((array1, array2))
print(f'Vertically stacked array: {vstacked_array}')
print(f'Vertically stacked array shape: {vstacked_array.shape}')

Horizontally stacked array: [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
Horizontally stacked array shape: (3, 6)
Vertically stacked array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Vertically stacked array shape: (6, 3)


15. Array Splitting

Use  np.split(), np.vsplit(), np.hsplit() or  np.array_split() to split an array.

In [40]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# split the array horizontally
hsplit_array = np.hsplit(my_array, 3)
print(f'Horizontally split array: {hsplit_array}')
for arr in hsplit_array:
    print(f'array: {arr}')

# split the array vertically
vsplit_array = np.vsplit(my_array, 3)
print(f'Vertically split array: {vsplit_array}')
for arr in vsplit_array:
    print(arr)

Horizontally split array: [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
array: [[1]
 [4]
 [7]]
array: [[2]
 [5]
 [8]]
array: [[3]
 [6]
 [9]]
Vertically split array: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


16. Array Duplicates

Use  np.repeat() or  np.tile() to perform repeated operations on an array.

In [42]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# repeat the array (element-wise)
repeated_array = np.repeat(my_array, 3)
print(f'Repeated array: {repeated_array}')

# tile the array
tiled_array = np.tile(my_array, 3)
print(f'Tiled array: {tiled_array}')


Repeated array: [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]
Tiled array: [[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [7 8 9 7 8 9 7 8 9]]


17. Array Sorting

Use  np.sort(), np.argsort(), np.lexsort(), , np.argmax() or  np.argmin() to sort and get the index of an array.

In [49]:
import numpy as np

# create an array
my_array = np.array([10,20,5,6,8])

# sort the array
sorted_array = np.sort(my_array)
print(f'Sorted array: {sorted_array}')

# get the indices of the sorted array
sorted_indices = np.argsort(my_array)
print(f'Sorted indices: {sorted_indices}')

for sor in sorted_indices:
    print(my_array[sor])

Sorted array: [ 5  6  8 10 20]
Sorted indices: [2 3 4 0 1]
5
6
8
10
20


18. Maximum and minimum values of an array

Use  np.max(), np.min(), np.argmax() or  np.argmin() to get the maximum and minimum values ​​of an array and their indices.

In [50]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# get the maximum value
max_value = np.max(my_array)
min_value = np.min(my_array)
print(f'Max value: {max_value}')
print(f'Min value: {min_value}')

# get the maximum and minimum values of their respective indexes
max_index = np.argmax(my_array)
min_index = np.argmin(my_array)
print(f'Max index: {max_index}')
print(f'Min index: {min_index}')

Max value: 9
Min value: 1
Max index: 8
Min index: 0


19. Array sum

Use  np.sum() or  np.cumsum() to sum or perform a cumulative sum calculation on the elements of an array.

In [51]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# get the sum of the array
sum_array = np.sum(my_array)
print(f'Sum of the array: {sum_array}')

# get the cumulative sum of the array
cumsum_array = np.cumsum(my_array)
print(f'Cumulative sum of the array: {cumsum_array}')

Sum of the array: 45
Cumulative sum of the array: [ 1  3  6 10 15 21 28 36 45]


20. Array Average

 Compute the average of the elements of an array using  np.mean() or  .np.average()

In [52]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# get the mean of the array
mean_value = np.mean(my_array)
print(f'Mean of the array: {mean_value}')

Mean of the array: 5.0


21. Median of an array

Use to  np.median() calculate the median of array elements.

In [53]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# get the median of the array
median_value = np.median(my_array)
print(f'Median of the array: {median_value}')

Median of the array: 5.0


22. Array Standard Deviation

Compute the standard deviation of the array elements using  np.std() .

In [54]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# get the standard deviation of the array
std_value = np.std(my_array)
print(f'Standard deviation of the array: {std_value}')

Standard deviation of the array: 2.581988897471611


23. Array Variance

np.var() Computes the variance of array elements

In [55]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# get the variance of the array
variance_value = np.var(my_array)
print(f'Variance of the array: {variance_value}')

Variance of the array: 6.666666666666667


24. Array row and column sum

Use to  np.sum(axis=0/1) calculate the row and column sums of an array.

axis = 1 means row

axis = 0 means column

In [59]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# calculate the the sum of the array along the rows
row_sum = np.sum(my_array, axis = 1)
print(f'Sum of the array along the rows: {row_sum}')

# calculate the the sum of the array along the columns
column_sum = np.sum(my_array, axis = 0)
print(f'Sum of the array along the columns: {column_sum}')

Sum of the array along the rows: [ 6 15 24]
Sum of the array along the columns: [12 15 18]


25. Array-specified axis calculation

Use  np.apply_along_axis() to apply a custom function to a specified axis of an array.

In [62]:
import numpy as np

# create an array
my_array = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# slef defined function
def custom_function(x):
    return x * 2

# apply the function to the array
new_array = np.apply_along_axis(custom_function, 0, my_array)
print(f'New array: {new_array}')

New array: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


26. Addition, substraction, multiplication and division of array elements

Use  np.add(), np.subtract(), , np.multiply(), np.divide() or  np.power() to add, subtract, multiply, and divide array elements.

In [64]:
import numpy as np

# create an array
array1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
array2 = np.array([[10,11,12],
                    [13,14,15],
                    [16,17,18]])

# add the arrays
sum_array = np.add(array1, array2)
print(f'Sum array: {sum_array}')

# subtract the arrays
diff_array = np.subtract(array1, array2)
print(f'Difference array: {diff_array}')

# multiply the arrays
prod_array = np.multiply(array1, array2)
print(f'Product array: {prod_array}')

# divide the arrays
quot_array = np.divide(array1, array2)
print(f'Quotient array: {quot_array}')

# power the arrays
pow_array = np.power(array1, 2)
print(f'Power array: {pow_array}')

Sum array: [[11 13 15]
 [17 19 21]
 [23 25 27]]
Difference array: [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
Product array: [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
Quotient array: [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
Power array: [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


27. Modulus of array elements

Use  np.mod() or  np.remainder() to perform the modulus operation on the elements of an array.

In [65]:
import numpy as np

# create an array
array1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

# modulus the array
mod_array = np.mod(array1, 2)
print(f'Modulus array: {mod_array}')

Modulus array: [[1 0 1]
 [0 1 0]
 [1 0 1]]


28. Absolute value of array elements

Use to  np.abs() calculate the absolute value of array elements.

In [66]:
import numpy as np

# create an array
array1 = np.array([-1,-2,-3,-5])

# absolute the array
abs_array = np.abs(array1)
print(f'Absolute array: {abs_array}')

Absolute array: [1 2 3 5]


29. Rounding array elements

Use  np.round(), np.floor(), , np.ceil() or  np.trunc() to round array elements.

In [68]:
import numpy as np

# create an array
array1 = np.array([1.22,2.5,3.6,4.9])

# round the array
round_array = np.round(array1)
print(f'Round array: {round_array}')

# floor the array
floor_array = np.floor(array1)
print(f'Floor array: {floor_array}')

# ceil the array
ceil_array = np.ceil(array1)
print(f'Ceil array: {ceil_array}')

# trunc the array
trunc_array = np.trunc(array1)
print(f'Trunc array: {trunc_array}')

Round array: [1. 2. 4. 5.]
Floor array: [1. 2. 3. 4.]
Ceil array: [2. 3. 4. 5.]
Trunc array: [1. 2. 3. 4.]


30. Array element comparison

Use  np.equal(), np.not_equal(), np.greater(), np.less(), , np.greater_equal() or  np.less_equal() to perform element-wise comparison operations.

In [71]:
import numpy as np

# create an array
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

# compare the arrays
compare_array = np.equal(array1, array2)
print(f'Equal array: {compare_array}')

# not equal the arrays
compare_array = np.not_equal(array1, array2)
print(f'Not equal array: {compare_array}')

# greater the arrays
compare_array = np.greater(array1, array2)
print(f'Greater array: {compare_array}')

# less the arrays
compare_array = np.less(array1, array2)
print(f'Less array: {compare_array}')

# greater or equal the arrays
compare_array = np.greater_equal(array1, array2)
print(f'Greater or equal array: {compare_array}')

# less or equal the arrays
compare_array = np.less_equal(array1, array2)
print(f'Less or equal array: {compare_array}')

Equal array: [False False False]
Not equal array: [ True  True  True]
Greater array: [False False False]
Less array: [ True  True  True]
Greater or equal array: [False False False]
Less or equal array: [ True  True  True]


31. Array logical operations

Use  np.logical_and(), np.logical_or(), np.logical_xor() or  np.logical_not() to perform logical operations.

In [74]:
import numpy as np

# create an array
array1 = np.array([True,False,True])
array2 = np.array([False,True,False])

# logical and the arrays
logical_and_array = np.logical_and(array1, array2)
print(f'Logical and array: {logical_and_array}')

# logical or the arrays
logical_or_array = np.logical_or(array1, array2)
print(f'Logical or array: {logical_or_array}')

# logical not the arrays
logical_not_array = np.logical_not(array1)
print(f'Logical not array: {logical_not_array}')

# logical xor the arrays
logical_xor_array = np.logical_xor(array1, array2)
print(f'Logical xor array: {logical_xor_array}')

Logical and array: [False False False]
Logical or array: [ True  True  True]
Logical not array: [False  True False]
Logical xor array: [ True  True  True]


32. Cumulative sum of array elements

Use  np.cumsum() or  np.cumprod() to sum or accumulate the elements of an array.

In [75]:
import numpy as np

# create an array
array1 = np.array([1,2,3])

# cumulative sum the array
cumsum_array = np.cumsum(array1)
print(f'Cumulative sum array: {cumsum_array}')

# cumulative product the array
cumprod_array = np.cumprod(array1)
print(f'Cumulative product array: {cumprod_array}')

Cumulative sum array: [1 3 6]
Cumulative product array: [1 2 6]


33. Array exponentiation

np.power() Raises an array to a power.

In [76]:
import numpy as np

# create an array
array1 = np.array([1,2,3])

# power the array
power_array = np.power(array1, 2)
print(f'Power array: {power_array}')

Power array: [1 4 9]


34. Array Inverse Operation

Use to  np.reciprocal() perform an inverse operation on an array.

In [81]:
import numpy as np

# create an array
array1 = np.array([1,4,9,16,0.25])

# reciprocal the array
reciprocal_array = np.reciprocal(array1) # 1/x
print(f'Reciprocal array: {reciprocal_array}')

Reciprocal array: [1.         0.25       0.11111111 0.0625     4.        ]


35. Array logarithm operations

Use  np.log(), np.log10() , or  np.log2() to perform logarithmic operations on an array.

In [82]:
import numpy as np

# create an array
array1 = np.array([1,100,1000])

# log the array
log_array = np.log(array1)
print(f'Log array: {log_array}')

# log10 the array
log10_array = np.log10(array1)
print(f'Log10 array: {log10_array}')

# log2 the array
log2_array = np.log2(array1)
print(f'Log2 array: {log2_array}')

Log array: [0.         4.60517019 6.90775528]
Log10 array: [0. 2. 3.]
Log2 array: [0.         6.64385619 9.96578428]


36. Array trigonometric functions

Use  np.sin(), np.cos(), np.tan(), np.arcsin(), np.arccos(), np.arctan() to perform trigonometric operations on arrays.

In [88]:
import numpy as np

# create an array
my_array = np.array([0,30,45,60,90])

# sin the array
sin_array = np.sin(my_array)
print(f'Sin array: {sin_array}')

# cos the array
print(f'Cos array: {np.cos(my_array)}')

# tan the array
print(f'Tan array: {np.tan(my_array)}')



Sin array: [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
Cos array: [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
Tan array: [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


37. Array Exponential function

Use  np.exp() or  np.exp2() to apply the exponential function to an array.

In [84]:
import numpy as np

# create an array
my_array = np.array([0,1,2,3,4,5,6,7,8,9])

# exp the array
exp_array = np.exp(my_array)
print(f'Exp array: {exp_array}')

# exp2 the array
exp2_array = np.exp2(my_array)
print(f'Exp2 array: {exp2_array}')

Exp array: [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
Exp2 array: [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


38. Array Hyperbolic functions

Use  np.sinh(), np.cosh(), np.tanh(), np.arcsinh(), np.arccosh(), np.arctanh() to perform hyperbolic function operations on arrays.

In [89]:
import numpy as np

# create an array
my_array = np.array([0,1,2,3,4,5,6,7,8,9])

# sinh the array
sinh_array = np.sinh(my_array)
print(f'Sinh array: {sinh_array}')

# cosh the array
cosh_array = np.cosh(my_array)
print(f'Cosh array: {cosh_array}')

# tanh the array
tanh_array = np.tanh(my_array)
print(f'Tanh array: {tanh_array}')



Sinh array: [0.00000000e+00 1.17520119e+00 3.62686041e+00 1.00178749e+01
 2.72899172e+01 7.42032106e+01 2.01713157e+02 5.48316123e+02
 1.49047883e+03 4.05154190e+03]
Cosh array: [1.00000000e+00 1.54308063e+00 3.76219569e+00 1.00676620e+01
 2.73082328e+01 7.42099485e+01 2.01715636e+02 5.48317035e+02
 1.49047916e+03 4.05154203e+03]
Tanh array: [0.         0.76159416 0.96402758 0.99505475 0.9993293  0.9999092
 0.99998771 0.99999834 0.99999977 0.99999997]


39. Array Linear algebra functions

 Perform linear algebra operations on arrays using  np.dot(), np.linalg.inv(), , np.linalg.det(), np.linalg.eigvals().np.linalg.solve()

In [91]:
import numpy as np

# create an array
array1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
array2 = np.array([[10,11,12],
                    [13,14,15],
                    [16,17,18]])

# dot the arrays
dot_array = np.dot(array1, array2)
print(f'Dot array: {dot_array}')

# linalg the arrays
# Computes the inverse of a square matrix.
linalg_array = np.linalg.inv(array1)
print(f'Linalg array: {linalg_array}')

# det the arrays
# Computes the determinant of a square matrix.
det_array = np.linalg.det(array1)
print(f'Det array: {det_array}')

# eig the arrays
# Computes the eigenvalues of a square matrix.
eig_array = np.linalg.eig(array1)
print(f'Eig array: {eig_array}')

# equations
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
x = np.linalg.solve(a,b)
print(f'Equation array: {x}')

Dot array: [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Linalg array: [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Det array: -9.51619735392994e-16
Eig array: EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -8.58274334e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
Equation array: [1. 2.]


40. Array Angle conversion

Use  np.degrees() or  np.radians() to convert degrees to radians.

In [92]:
import numpy as np

# create an array
radians_array = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])

# convert the array to degrees
degrees_array = np.degrees(radians_array)
print(f'Degrees array: {degrees_array}')

# convert the array to radians
radians_array = np.radians(degrees_array)
print(f'Radians array: {radians_array}')

Degrees array: [  0.  90. 180. 270. 360.]
Radians array: [0.         1.57079633 3.14159265 4.71238898 6.28318531]


41. Array deduplication

Use  np.unique() to deduplicate the array.


In [93]:
import numpy as np

# create an array
my_array = np.array([1,2,2,3,3])

# unique the array
unique_array = np.unique(my_array)
print(f'Unique array: {unique_array}')


Unique array: [1 2 3]


44. Array copy 

Use  np.copy() or  np.ndarray.copy() copy the array.

In [94]:
import numpy as np

# create an array
my_array = np.array([1,2,3,4,5])

# copy the array
copied_array = np.copy(my_array)
print(f'Copied array: {copied_array}')

# another way to copy the array
copied_array = my_array.copy()
print(f'Copied array: {copied_array}')

Copied array: [1 2 3 4 5]
Copied array: [1 2 3 4 5]


45. Array Insertion

Use  np.insert() or  np.append() to insert into an array.

In [95]:
import numpy as np

# create an array
my_array = np.array([1,2,3,4,5])

# insert a value at a specific index
inserted_array = np.insert(my_array, 2, [10,11])
print(f'Inserted array: {inserted_array}')

# insert the values at the end of the array
inserted_array = np.append(my_array, [10,11])
print(f'Inserted array: {inserted_array}')

Inserted array: [ 1  2 10 11  3  4  5]
Inserted array: [ 1  2  3  4  5 10 11]


47. Array Deletion

Use  np.delete() to delete arrays.

In [96]:
import numpy as np

# create an array
my_array = np.array([1,2,3,4,5])

# delete a value at a specific index
deleted_array = np.delete(my_array, 2)
print(f'Deleted array: {deleted_array}')

Deleted array: [1 2 4 5]
